version: '3'
services:
  dev-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: badgeload
      MYSQL_DATABASE: badgeload
      MYSQL_USER: badgeload
      MYSQL_PASSWORD: badgeload